# Configuration du site
title: Documentation Équipe IFRI 2025
description: Documentation officielle de l'équipe IFRI pour l'année académique 2025
baseurl: "/2025-Team-IFRI-Docs"
url: "https://2025-team-ifri-docs.github.io"

# Configuration Jekyll - important pour le traitement des fichiers
markdown: kramdown
theme: jekyll-theme-minimal
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-seo-tag

# Inclusions spécifiques
include:
  - .nojekyll
  - Documentation

# Valeurs par défaut pour les layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "Documentation"
    values:
      layout: "default"
      path: ""
    values:
      layout: "default"
  - scope:
      path: "Documentation"
    values:
      layout: "default"
