# Configuration du site
title: Documentation Équipe IFRI 2025
description: Documentation officielle de l'équipe IFRI pour l'année académique 2025
baseurl: "/2025-Team-IFRI-Docs"
url: "https://2025-team-ifri-docs.github.io"

# Configuration de build
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

# Plugins
plugins:
  - jekyll-seo-tag

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md

# Inclusions spécifiques - important pour inclure les fichiers de documentation
include:
  - .nojekyll
  - Documentation

# Valeurs par défaut
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "Documentation"
    values:
      layout: "default"
