title: Documentation Équipe IFRI 2025
description: Documentation officielle de l'équipe IFRI pour l'année 2025
baseurl: "/2025-Team-IFRI-Docs"

# Simplifier la configuration
markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag

include:
  - Documentation
# Plugins
plugins:
  - jekyll-seo-tag

# Inclusions spécifiques
include:
  - .nojekyll
  - Documentation

# Valeurs par défaut pour les layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "Documentation"
    values:
      layout: "default"
      path: ""
    values:
      layout: "default"
  - scope:
      path: "Documentation"
    values:
      layout: "default"
