# Configuration du site
title: Documentation Équipe IFRI 2025
description: Documentation officielle de l'équipe IFRI pour l'année académique 2025
baseurl: "/2025-Team-IFRI-Docs"
url: "https://2025-team-ifri-docs.github.io"

# Structure de navigation
collections:
  documentation:
    output: true
    permalink: /:collection/:path/

# Configuration de build
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge

# Plugins
plugins:
  - jekyll-seo-tag

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - README.md

# Inclusions spécifiques
include:
  - .nojekyll

# Collections pour la documentation
collections:
  documentation:
    output: true
    permalink: /:collection/:path/
